### ISSUE TITLE
Czechia Parser: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1579]
Was testing a potential backfilling fix, and ran into the following error for Czechia. Looks like a quick one!

```
[ERROR] AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/var/task/czechia.py", line 132, in lambda_handler
    return parsing_lib.run_lambda(event, context, parse_cases)
  File "/opt/python/parsing_lib.py", line 331, in run_lambda
    common_lib.complete_with_error(
  File "/opt/python/common_lib.py", line 98, in complete_with_error
    raise exception
  File "/opt/python/parsing_lib.py", line 316, in run_lambda
    count_created, count_updated = write_to_server(
  File "/opt/python/parsing_lib.py", line 140, in write_to_server
    batch = batch_of(cases, cases_batch_size)
  File "/opt/python/parsing_lib.py", line 124, in batch_of
    batch.append(next(cases))
  File "/opt/python/parsing_lib.py", line 227, in <genexpr>
    return (case for case in case_data if case_is_within_range(case, start, end))
  File "/opt/python/parsing_lib.py", line 105, in prepare_cases
    for case in cases:
  File "/var/task/czechia.py", line 116, in parse_cases
    "query": convert_location(row[_REGION], row[_DISTRICT])
  File "/var/task/czechia.py", line 71, in convert_location
    district = district.replace("0", "-", 1)
```

**Comment by AnyaLindstromBattle** [comment]
@abhidg this is the same error we had when there was a chunking issue (i.e. when there was a 'd' in a line below the header). Can you take a look?

**Comment by AnyaLindstromBattle** [comment]
Having said that, even though it's very similar to the chunking-related error, this may actually be a parser issue. Will submit PR.
