### ISSUE TITLE
ECONNREFUSED when trying to upload cases in Batch

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1745]
Get this error when trying to upload Estonia, through Batch job submission

```
Current speed: 33 cases/sec
Sending 250 cases, total so far: 2000
Current speed: 33 cases/sec
Sending 250 cases, total so far: 2250
Error sending cases to server, status=500, response=connect ECONNREFUSED 10.100.204.152:80
Updating upload via https://dev-data.covid-19.global.health/api/sources/5f60bd4da93dee697cd194be/uploads/607760e640e4b4384d68bef1
Error sending cases to server, status=500, response=connect ECONNREFUSED 10.100.204.152:80
Updating upload via https://dev-data.covid-19.global.health/api/sources/5f60bd4da93dee697cd194be/uploads/607760e640e4b4384d68bef1
Traceback (most recent call last):
File "./retrieval/retrieval.py", line 300, in <module>
  run_retrieval(tempdir=(EFS_PATH if len(sys.argv) == 1 else sys.argv[1]))
File "./retrieval/retrieval.py", line 288, in run_retrieval
  invoke_parser(
File "./retrieval/retrieval.py", line 204, in invoke_parser
  importlib.import_module(python_module).event_handler(payload)
File "./parsing/estonia/estonia.py", line 111, in event_handler
  return parsing_lib.run(event, parse_cases)
File "/app/retrieval/../common/parsing_lib.py", line 315, in run
  common_lib.complete_with_error(
File "/app/retrieval/../common/common_lib.py", line 102, in complete_with_error
  raise exception
File "/app/retrieval/../common/parsing_lib.py", line 300, in run
  count_created, count_updated = write_to_server(
File "/app/retrieval/../common/parsing_lib.py", line 159, in write_to_server
  common_lib.complete_with_error(
File "/app/retrieval/../common/common_lib.py", line 102, in complete_with_error
  raise exception
RuntimeError: Error sending cases to server, status=500, response=connect ECONNREFUSED 10.100.204.152:80
```

﻿

**Comment by abhidg** [comment]
Retried Estonia, and now it's socket hang up

```
Sending 250 cases, total so far: 2000
--
Current speed: 52 cases/sec
Sending 250 cases, total so far: 2250
Current speed: 46 cases/sec
Sending 250 cases, total so far: 2500
Current speed: 42 cases/sec
Sending 250 cases, total so far: 2750
Error sending cases to server, status=500, response=socket hang up
Updating upload via https://dev-data.covid-19.global.health/api/sources/5f60bd4da93dee697cd194be/uploads/6078aa1b40e4b4d2a068befa
Error sending cases to server, status=500, response=socket hang up
Updating upload via https://dev-data.covid-19.global.health/api/sources/5f60bd4da93dee697cd194be/uploads/6078aa1b40e4b4d2a068befa
```

:thinking:  What'll the next error be? It appears to stop around the same time, suggesting a memory issue

**Comment by abhidg** [comment]
Possibly related to #961

**Comment by iamleeg** [comment]
If #961, then one solution is to ensure _all_ operations that could potentially return more than one case are paged, including the new `downloadAsync` operation. That would complicate the (weird, standalone) worker task some more which is not my favourite idea. But then tracking down unidentifiable heap growth in v8 is also not my favourite idea.

**Comment by abhidg** [comment]
Removing https://www.npmjs.com/package/longjohn fixed Estonia ingestion, will try USA

**Comment by iamleeg** [comment]
> it is not recommended to use longjohn in production. The data collection puts a lot of strain on V8's garbage collector

sounds legit

**Comment by abhidg** [comment]
Appears to be fixed by https://github.com/globaldothealth/list/commit/c0c19e9973a80b0161b6a72ffd0c08e52cd4fa26

**Comment by abhidg** [comment]
It's back! When trying to backfill, see log `6082bf02b5ccb0fdd487d36b-dev/default/c21d87c9fbff4f9dbabdb4488d8f58f8` in Batch

```
2021-04-28T00:02:11.663+01:00 | Sending 250 cases, total so far: 39750
2021-04-28T00:02:11.663+01:00 | Error sending cases to server, status=500, response=connect ECONNREFUSED 10.100.204.152:80
2021-04-28T00:02:11.663+01:00 | Updating upload via https://dev-data.covid-19.global.health/api/sources/6082bf02b5ccb0fdd487d36b/uploads/60888f9d4eaa1969cbdca42d
2021-04-28T00:02:11.663+01:00 | Error sending cases to server, status=500, response=connect ECONNREFUSED 10.100.204.152:80
```

**Comment by abhidg** [comment]
Mitigated by the following:

1. Moving Mapbox geocoding into its own service which took some load off data-service
2. 'longjohn' was a dependency in dev, which was for debugging purposes, removing it solved the issue on dev.
3. There are now very few occasions when there are data service crashes, adding exponential backoff solved it.
4. Finalising the upload was failing because of the authentication token expiring, adding reauthentication fixed this issue.

Data service still crashes on simultaneous data ingestion, but fixing that is out of scope with current thread, so closing this.
