### ISSUE TITLE
Data export is broken

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1819]
Data is not being exported since 21 March 2021. Possibly related to ADI breakage. S3 bucket https://s3.console.aws.amazon.com/s3/buckets/covid-19-data-export?region=us-east-1&prefix=archive/&showversions=false

**Comment by abhidg** [comment]
CloudWatch log

```
[ERROR] FileExistsError: [Errno 17] File exists: '/mnt/efs/in/'
Traceback (most recent call last):
  File "/var/task/app.py", line 98, in lambda_handler
    setup_directories()
  File "/var/task/app.py", line 24, in setup_directories
    os.makedirs("/mnt/efs/in/")
  File "/var/lang/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
```
