### ISSUE TITLE
Handle encoding None in parser_lib

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1969]
In some cases, the encoding detection fails and returns None. This causes `codecs.getreader()` to fail as it needs an encoding.

We should either:
* Pick a default encoding in this case, such as utf-8
* Let the individual parser override the encoding detection.

This bug caused Argentina parser failure on 2021-06-30

```
Downloading CSV content from https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.zip
--
Download finished
Guessing mimetype of https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.zip
File seems to be a zip file, decompressing it now
detecting encoding of retrieved content.
Source encoding is presumably {'encoding': None, 'confidence': 0.0, 'language': None}
Traceback (most recent call last):
File "./retrieval/retrieval.py", line 308, in <module>
run_retrieval(tempdir=(TEMP_PATH if len(sys.argv) == 1 else sys.argv[1]))
File "./retrieval/retrieval.py", line 288, in run_retrieval
file_names_s3_object_keys = retrieve_content(
File "./retrieval/retrieval.py", line 160, in retrieve_content
text_stream = codecs.getreader(detected_enc['encoding'])(bytesio)
File "/usr/local/lib/python3.8/codecs.py", line 1013, in getreader
return lookup(encoding).streamreader
TypeError: lookup() argument must be str, not None
```

**Comment by abhidg** [comment]
Closed by de9731372382356a0abc6bb3934ed249ddb1cd9d
