### ISSUE TITLE
Colombia ingestion failing with 504

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2005]
Duplicate case id is attempting to be written and failing
```
(node:1) UnhandledPromiseRejectionWarning: BulkWriteError: E11000 duplicate key error collection: covid19.caserevisions index: case._id_1_case.revisionMetadata.revisionNumber_-1 dup key: { case._id: ObjectId('60e384c6496aca98df7a2f68'), case.revisionMetadata.revisionNumber: 1 }
    at UnorderedBulkOperation.handleWriteError (/usr/src/app/node_modules/mongodb/lib/bulk/common.js:1257:9)
    at UnorderedBulkOperation.handleWriteError (/usr/src/app/node_modules/mongodb/lib/bulk/unordered.js:117:18)
    at resultHandler (/usr/src/app/node_modules/mongodb/lib/bulk/common.js:521:23)
    at handler (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /usr/src/app/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/usr/src/app/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.ondata (_stream_readable.js:718:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
```

**Comment by abhidg** [comment]
Fixed by adding a try/catch when trying to write case revision metadata
