### ISSUE TITLE
Ingestion failing with module not found

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2532]
Ingestion failing with module not found

```


Traceback (most recent call last):
--
  File "./retrieval/retrieval.py", line 47, in <module>
    import common_lib
ModuleNotFoundError: No module named 'common_lib'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./retrieval/retrieval.py", line 53, in <module>
    import common_lib
  File "/app/retrieval/../common/common_lib.py", line 16, in <module>
    import common.ingestion_logging as logging
ModuleNotFoundError: No module named 'common'
```

**Comment by abhidg** [comment]
Changing common.ingestion_logging -> ingestion_logging fixes this but breaks the test, so that must be why the path hack was there.
