### ISSUE TITLE
Authorization error in clean-adi-source-data

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2539]
```
Traceback (most recent call last):
  File "./clean_old_ingestion_source_files.py", line 43, in <module>
    main(endpoint_url)
  File "./clean_old_ingestion_source_files.py", line 18, in main
    sources_and_ages = {r.ingestion_source_id(): r.oldest_file_age(datetime.today()) for r in get_schedule_rules(endpoint_url) if r.is_ingestion_rule()}
  File "./clean_old_ingestion_source_files.py", line 14, in get_schedule_rules
    return event_bridge.get_schedule_rules()
  File "/app/aws_access/EventBridgeClient.py", line 154, in get_schedule_rules
    return [EventBridgeClient.rule_for_description(d) for d in self.get_rule_descriptions()]
  File "/app/aws_access/EventBridgeClient.py", line 151, in get_rule_descriptions
    return self.aws_client.list_rules().get("Rules")
  File "/app/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/app/.venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ListRules operation: User: arn:aws:sts::612888738066:assumed-role/gdh-batch-instance-role/i-02aed2dd2308aa610 is not authorized to perform: events:ListRules on resource: arn:aws:events:us-east-1:612888738066:rule/* because no identity-based policy allows the events:ListRules action
```

**Comment by iamleeg** [comment]
Ah right, I picked the default batch execution role for this task. I will create a new role.

**Comment by iamleeg** [comment]
Anyone able to pair with me on this? I have added the ListRules permission to the policy and the script still fails as it doesn't have the ListRules permission.
