### ISSUE TITLE
Import Argentina case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#508]
https://datos.gob.ar/dataset/salud-covid-19-casos-registrados-republica-argentina/archivo/salud_fd657d02-a33a-498b-a91b-2ef1a68b8d16

**Comment by z023** [comment]
Set up Argentina and triggered retrieval. Got an error 'Error: Request failed with status code 500'.
Related to #1124?

**Comment by attwad** [comment]
That's different although still size-related, it seems that Argentina CSV is about 400Mb and we're hitting some lambda limits when retrieving that file in our retrieval function:

```
Downloading CSV content from https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.csv
[ERROR] MemoryError
Traceback (most recent call last):
  File "/var/task/retrieval.py", line 262, in lambda_handler
    file_name, s3_object_key = retrieve_content(
  File "/var/task/retrieval.py", line 116, in retrieve_content
    r = requests.get(url, headers=headers)
  File "/var/task/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/var/task/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/task/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 683, in send
    r.content
  File "/var/task/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
```

I will bump the memory available to the function from 512MB to some higher number.

**Comment by attwad** [comment]
OK 768MB failed but 1GB worked

```
2020-09-29T08:49:04.062+02:00 | Downloading CSV content from https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.csv
-- | --
  | 2020-09-29T08:51:06.064+02:00 | Download finished
  | 2020-09-29T08:51:06.064+02:00 | Guessing mimetype of https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.csv
  | 2020-09-29T08:51:06.065+02:00 | detecting encoding of retrieved content.
  | 2020-09-29T08:51:20.946+02:00 | Source encoding is presumably {'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}
  | 2020-09-29T08:51:50.070+02:00 | Uploaded source content to s3://epid-sources-raw/5f72318c5c17a09229e3cb54/2020/09/29/0651/content.csv
  | 2020-09-29T08:51:50.070+02:00 | Invoking parser (ARN: epid-ingestion-ArgentinaParsingFunction-PB9EAPNPO7CE)
```

**Comment by attwad** [comment]
OK we could ingest 139250 cases in 900s but argentina has way too many cases so it will have to be backfilled with #1124 first.

**Comment by z023** [comment]
IDs 1383222 and 1333926 need excluding from future ingestions.

**Comment by Mougk** [comment]
@fojackson8 take a look here. See example code for Japan to exclude ID's here: https://github.com/globaldothealth/list/pull/1278/files/42c91a2f98db54015c685ed9bcbdec235741bf2e

**Comment by z023** [comment]
I've realised half of Argentina cases are still missing even after backfilling. Those 2 IDs weren't ingested anyway.
