### ISSUE TITLE
505 error when edit a line list case

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#940]
Steps to recreate
1. Pick a line list case
2. Edit a field (i changed the age)
3. Submit

Screen hangs and then provides a 505 error

Browser: Chroms
Curator: sratcliffe@google.com

**Comment by sratcliffe118** [comment]
Error message

{"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n at e.exports (https://dev-curator.ghdsi.org/static/js/2.23ec0edc.chunk.js:2:825462)\n at e.exports (https://dev-curator.ghdsi.org/static/js/2.23ec0edc.chunk.js:2:1416822)\n at XMLHttpRequest.p.onreadystatechange (https://dev-curator.ghdsi.org/static/js/2.23ec0edc.chunk.js:2:824295)","config":{"url":"/api/cases/5f50397cef6fe57a3838ffab","method":"put","data":"{\"caseReference\":{\"verificationStatus\":\"VERIFIED\",\"sourceId\":\"5f5039002761b26f9cb91d41\",\"sourceUrl\":\"https://raw.githubusercontent.com/openZH/covid_19/master/fallzahlen_kanton_alter_geschlecht_csv/COVID19_Fallzahlen_Kanton_ZH_alter_geschlecht.csv\",\"uploadId\":\"5f5039392761b20e41b91da1\",\"additionalSources\":[]},\"demographics\":{\"gender\":\"Female\",\"ageRange\":{\"start\":54,\"end\":54},\"nationalities\":[]},\"location\":{\"country\":\"Switzerland\",\"administrativeAreaLevel1\":\"Zurich\",\"geoResolution\":\"Admin1\",\"name\":\"Zurich canton\",\"geometry\":{\"longitude\":8.651071,\"latitude\":47.42568}},\"events\":[{\"name\":\"confirmed\",\"dateRange\":{\"start\":\"Mon Jul 06 2020 01:00:00 GMT+0100 (British Summer Time)\",\"end\":\"Mon Jul 06 2020 01:00:00 GMT+0100 (British Summer Time)\"}}],\"symptoms\":{\"values\":[]},\"preexistingConditions\":{\"values\":[]},\"transmission\":{},\"travelHistory\":{},\"genomeSequences\":[],\"pathogens\":[]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}

**Comment by axmb** [comment]
From logs:

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwi
ng inside of an async function without a catch block, or by rejecting a promise which was not handled with .ca
tch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=
strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:1) UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key error collection: covid19.caserevi
sions index: case._id_1_case.revisionMetadata.revisionNumber_-1 dup key: { case._id: ObjectId('5f50397cef6fe57a3838ffab'), case.revisionMetadata.revisionNumber: 0 }
    at Function.create (/usr/src/app/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/usr/src/app/node_modules/mongodb/lib/utils.js:123:22)
    at /usr/src/app/node_modules/mongodb/lib/operations/common_functions.js:265:39
    at handler (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /usr/src/app/node_modules/mongodb/lib/cmap/connection_pool.js:356:13
    at handleOperationResult (/usr/src/app/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:275:5)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.ondata (_stream_readable.js:716:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
```

Something about a previous request (I believe a `batchUpdate` flipping verification) put these cases into a state where the case object didn't have its revision number incremented, which occurs at the end of the batchUpdate request, but a `caserevision` _was_ saved. Because revisions are keyed on `_id:revisionNumber`, subsequent updates to these cases fail with the above error.

**Comment by allysonjp715** [comment]
Hopefully after #1037 the cases can no longer get in a bad state. Leaving this open to track if there is a way to fail more gracefully if there are duplicate case revisions created.

**Comment by axmb** [comment]
This should be really rare following the aforementioned logic changes and server upgrades, which reduce the likelihood of requests failing in a bad state.

To move from "really rare" to totally fixed, we'd want to make the creation of case revisions transactional with the corresponding updates to the core case document. Right now, the revisions are created before applying the operation (i.e. update/delete), but those changes aren't rolled back if the actual mutation fails.
