### ISSUE TITLE
Can't navigate to last page of linelist

### ISSUE THREAD

**Issue by axmb** [globaldothealth/list#942]
**Describe the bug**
When I try to go to the last linelist page (by hitting the "last page" button at the bottom), the page errors.

**Additional context**
I'm seeing the following in logs:

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
MongoError: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.
    at MessageStream.messageHandler (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:266:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.ondata (_stream_readable.js:716:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 6, high_: 1599148739 },
  ok: 0,
  code: 96,
  codeName: 'OperationFailed',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 6, high_: 1599148739 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
```

Seems like we're perhaps trying to hold and sort the entirety of linelist data in memory as a result of the request.

**Comment by attwad** [comment]
Seems like we're missing an index on the time we use to sort with.

**Comment by attwad** [comment]
Official docs about this problem:
https://docs.mongodb.com/manual/reference/limits/#Sort-Operations

**Comment by attwad** [comment]
Ah, I had forgotten about the collation, I got it to work now, will send the PR.

**Comment by attwad** [comment]
FTR the index I created is:

`db.cases.createIndex({'revisionMetadata.creationMetadata.date': -1}, {collation: {locale: 'en_US', strength: 2}})`

And now https://dev-curator.ghdsi.org/api/cases/?limit=50&page=1404 works
